name: Swift Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.5'

      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install

      - name: Build and run tests
        run: |
          xcodebuild -workspace HealthCalculator.xcworkspace \
                     -scheme HealthCalculator \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
                     clean test

